# Generated by Django 3.0.3 on 2020-06-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200616_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='48px * 48px 크기의 png/jpg 파일을 업로드 해주세요', upload_to='accounts/avatar/%Y/%m/%d'),
        ),
    ]
